configuration:
  width: 450
  height: 450
  luminosity-label: '59.8 fb^{-1} (13 TeV)'
  experiment: " CMS"
  experiment-label-paper: true
  extra-label: "Preliminary"
  root: ''
  luminosity: 1
  luminosity-error: 0.025
  error-fill-style: 3154
  error-fill-color: "#ee556270"
  staterror-fill-style: 3145
  staterror-fill-color: 7
  ratio-fit-error-fill-style: 1001
  ratio-fit-error-fill-color: "#aa556270"
  ratio-fit-line-color: "#0B486B"
  blinded-range-fill-color: "#29556270"
  blinded-range-fill-style: 1001
  yields-table-align: v
  book-keeping-file: 'plots.root'
  yields-table-numerical-precision-yields: 2

files: 
  include: ['files.yml']

systematics:
  - norm_diboson: {type: const, value: 1.3, on: 'diboson'}
  - norm_singletop: {type: const, value: 1.3, on: 'singletop|singletw'}
  - norm_tt: {type: const, value: 1.042, on: 'ttbarsignal|ttbarbg'}
  - norm_ttbarX: {type: const, value: 1.3, on: 'ttbarX'}
  - norm_wjets: {type: const, value: 1.3, on: 'wjets'}
  - BFRAG: {type: shape, on: 'ttbarsignal|ttbarbg|singletw'}
  - BFRAG_CENTRAL: {type: shape, on: 'ttbarsignal|ttbarbg|singletw'}
  - BSEMILEP: {type: shape, on: 'ttbarsignal|ttbarbg|singletw'}
  - BTAG_JES
  - BTAG_LJET_CORR
  - BTAG_LJET_UNCORR2018
  - BTAG_PILEUP
  - BTAG_STATISTIC2018
  - BTAG_TYPE3
  - ELE_ID
  - ELE_RECO
  - ELE_SCALE
  - ELE_SMEAR
  - JEREta02018
  - JEREta12018
  - JESAbsoluteMPFBias
  - JESAbsoluteScale
  - JESAbsoluteStat2018
  - JESFlavorPureBottom
  - JESFlavorPureCharm
  - JESFlavorPureGluon
  - JESFlavorPureQuark
  - JESFragmentation
  - JESPileUpDataMC
  - JESPileUpPtBB
  - JESPileUpPtEC1
  - JESPileUpPtRef
  - JESRelativeBal
  - JESRelativeFSR
  - JESRelativeJEREC12018
  - JESRelativePtBB
  - JESRelativePtEC12018
  - JESRelativeSample2018
  - JESRelativeStatEC2018
  - JESRelativeStatFSR2018
  - JESSinglePionECAL
  - JESSinglePionHCAL
  - JESTimePtEta2018
  - JESUserDefinedHEM1516
  - L1PREFIRING_ECAL
  - L1PREFIRING_MUON
  - MASS: {type: shape, on: 'ttbarsignal|ttbarbg'}
  - WIDTH_30: {type: shape, on: 'ttbarsignal|ttbarbg|singletw'}
  - MATCH: {type: shape, on: 'ttbarsignal|ttbarbg'}
  - MEFACSCALE: {type: shape, on: 'ttbarsignal|ttbarbg'}
  - MEFACSCALE_ST: {type: shape, on: 'singletw'}
  - MEFACSCALE_Z: {type: shape, on: 'dy'}
  - MERENSCALE: {type: shape, on: 'ttbarsignal|ttbarbg'}
  - MERENSCALE_ST: {type: shape, on: 'singletw'}
  - MERENSCALE_Z: {type: shape, on: 'dy'}
  - MUON_ID_STAT2018
  - MUON_ID_SYST
  - MUON_ISO_STAT2018
  - MUON_ISO_SYST
  - MUON_SCALE_DELTAM
  - MUON_SCALE_EWK2
  - MUON_SCALE_EWK
  - MUON_SCALE_STAT2018
  - MUON_SCALE_ZPT
  - PDF_ALPHAS: {type: shape, on: 'ttbarsignal|ttbarbg|singletw'}
  - PSSCALE_WEIGHT_14: {type: shape, on: 'ttbarsignal|ttbarbg'}
  - PSSCALE_WEIGHT_3: {type: shape, on: 'ttbarsignal|ttbarbg'}
  - PSSCALE_WEIGHT_ST_14: {type: shape, on: 'singletw'}
  - PSSCALE_WEIGHT_ST_3: {type: shape, on: 'singletw'}
  - PU
  - TOP_PT: {type: shape, on: 'ttbarsignal|ttbarbg'}
  - TRIG_EE2018_STAT
  - TRIG_EE2018_SYS
  - TRIG_EMU2018_STAT
  - TRIG_EMU2018_SYS
  - TRIG_MUMU2018_STAT
  - TRIG_MUMU2018_SYS
  - UETUNE: {type: shape, on: 'ttbarsignal|ttbarbg|singletw'}
  - UNCLUSTERED2018

plots:
  include: ['histos_yield.yml', 'histos_control.yml']
  #include: ['histos_yield.yml']

legend:
  position: [0.35, 0.70, 0.94, 0.88]
  columns: 4

groups:
  include: ['groups.yml']
