'data.root':
  type: data
  pretty-name: 'Data'
  group: Gdata

'ttbarsignal.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttll
  yields-group: '1t#bar{t}\;(\ell\ell)'
  order: 9

'ttbarsignalplustau_Bin0.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin0
  yields-group: '0t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin0}'
  order: 9

'singletw_Bin0.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin0
  yields-group: '0t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin0}'
  order: 9

'ttbarsignalplustau_Bin1.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin1
  yields-group: '0t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin1}'
  order: 10

'singletw_Bin1.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin1
  yields-group: '0t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin1}'
  order: 10

'ttbarsignalplustau_Bin2.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin2
  yields-group: '0t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin2}'
  order: 11

'singletw_Bin2.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin2
  yields-group: '0t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin2}'
  order: 11

'ttbarsignalplustau_Bin3.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin3
  yields-group: '0t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin3}'
  order: 12

'singletw_Bin3.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin3
  yields-group: '0t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin3}'
  order: 12

'ttbarsignalplustau_Bin4.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin4
  yields-group: '0t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin4}'
  order: 13

'singletw_Bin4.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin4
  yields-group: '0t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin4}'
  order: 13

'ttbarsignalplustau_Bin5.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin5
  yields-group: '0t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin5}'
  order: 14

'singletw_Bin5.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin5
  yields-group: '0t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin5}'
  order: 14

'ttbarsignalplustau_Bin6.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin6
  yields-group: '0t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin6}'
  order: 15

'singletw_Bin6.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin6
  yields-group: '0t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin6}'
  order: 15

'ttbarsignalplustau_Bin7.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin7
  yields-group: '0t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin7}'
  order: 16

'singletw_Bin7.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin7
  yields-group: '0t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin7}'
  order: 16

'ttbarsignalplustau_Bin8.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin8
  yields-group: '0t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin8}'
  order: 17

'singletw_Bin8.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin8
  yields-group: '0t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin8}'
  order: 17

'ttbarsignalplustau_Bin9.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin9
  yields-group: '0t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin9}'
  order: 18

'singletw_Bin9.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin9
  yields-group: '0t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin9}'
  order: 18

'ttbarsignalplustau_Bin10.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin10
  yields-group: '1t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin10}'
  order: 19

'singletw_Bin10.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin10
  yields-group: '1t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin10}'
  order: 19

'ttbarsignalplustau_Bin11.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin11
  yields-group: '1t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin11}'
  order: 20

'singletw_Bin11.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin11
  yields-group: '1t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin11}'
  order: 20

'ttbarsignalplustau_Bin12.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin12
  yields-group: '1t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin12}'
  order: 21


'singletw_Bin12.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin12
  yields-group: '1t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin12}'
  order: 21

'ttbarsignalplustau_Bin13.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin13
  yields-group: '1t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin13}'
  order: 22

'singletw_Bin13.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin13
  yields-group: '1t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin13}'
  order: 22

'ttbarsignalplustau_Bin14.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin14
  yields-group: '1t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin14}'
  order: 23

'singletw_Bin14.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin14
  yields-group: '1t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin14}'
  order: 23

'ttbarsignalplustau_Bin15.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin15
  yields-group: '1t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin15}'
  order: 24

'singletw_Bin15.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin15
  yields-group: '1t#bar{t}\;(\ell\ell)\;+tW #textrm{Bin15}'
  order: 24

'ttbarbgFromDilepton.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttbkg
  yields-group: '2t#bar{t}\;(\textrm{not dileptonic})'
  order: 7

'ttbarbgFromLjets.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttbkg
  yields-group: '2t#bar{t}\;(\textrm{not dileptonic})'
  order: 6

'ttbarbgFromHadronic.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttbkg
  yields-group: '2t#bar{t}\;(\textrm{not dileptonic})'
  order: 5

'singletw.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gst
  yields-group: '3Single top'
  order: 4

'singletop.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gother
  yields-group: '5Other'
  order: 4

'dy.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gdy
  yields-group: '4Z+jets'
  order: 8

'ttbarX.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gother
  yields-group: '5Other'
  order: 3

'diboson.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gother
  yields-group: '5Other'
  order: 2

'wjets.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gother
  yields-group: '5Other'
  order: 1

