configuration:
  width: 450
  height: 450
  luminosity-label: '59.8 fb^{-1} (13 TeV)'
  experiment: " CMS"
  experiment-label-paper: true
  extra-label: "  Preliminary"
  root: '.'
  luminosity: 1
  luminosity-error: 0
  error-fill-style: 3154
  error-fill-color: "#ee556270"
  ratio-fit-error-fill-style: 1001
  ratio-fit-error-fill-color: "#aa556270"
  ratio-fit-line-color: "#0B486B"
  blinded-range-fill-color: "#29556270"
  blinded-range-fill-style: 1001
  yields-table-align: v
  book-keeping-file: 'plots.root'
  yields-table-numerical-precision-yields: 2

groups:
  include: ['groups.yml']

files:
  include: ['postfit_files.yml']

systematics:
  #- postfit
  - total: {type: shape, on: 'ttbartwbb4linclusive_Bin0'}

plots:
  include: ['postfit_histos.yml']

legend:
  #position: [0.18, 0.72, 0.88, 0.86]
  #position: [0.35, 0.74, 0.94, 0.88]
  position: [0.38, 0.63, 0.93, 0.88]
  columns: 3
