'GOneJ_TwoB_postfit':
  y-axis: "Events"
  #y-axis-format: "%1% / %2$.2f"
  y-axis-format: "%1% / bin"
  save-extensions: ['pdf', 'png']
  for-yields: true
  yields-table-order: 2
  yields-title: '$Post-fit$'
  x-axis: 'm_{lb}^{minimax}'
  ratio-y-axis-range: [0.945, 1.055]
  ratio-y-axis-auto-range: true
  post-fit: true
  log-y: true
  labels:
    - {text: 'Post-fit e#mu', position: [0.2, 0.806], size: 17, font: 44}

'GOneJ_TwoB_prefit':
  y-axis: "Events"
  #y-axis-format: "%1% / %2$.2f"
  y-axis-format: "%1% / bin"
  save-extensions: ['pdf', 'png']
  for-yields: true
  yields-table-order: 2
  yields-title: '$Pre-fit$'
  x-axis: 'm_{lb}^{minimax}'
  ratio-y-axis-range: [0.945, 1.055]
  ratio-y-axis-auto-range: true
  post-fit: true
  log-y: true
  labels:
    - {text: 'Pre-fit e#mu', position: [0.2, 0.806], size: 17, font: 44}
