#jet multiplicities
'h_ncleanjetspass_notausf_S1':
  y-axis-format: "%1% / bin"
  log-y: true 
  sort-by-yields: true 
  save-extensions: ['pdf', 'png']

'h_ncleanjetspass_S2':
  y-axis-format: "%1% / bin"
  log-y: true 
  sort-by-yields: true 
  save-extensions: ['pdf', 'png']

'h_ncleanjetspass_S3':
  y-axis-format: "%1% / bin"
  log-y: true 
  sort-by-yields: true 
  save-extensions: ['pdf', 'png']

'h_ncleanjetspass_S4':
  y-axis-format: "%1% / bin"
  log-y: true 
  sort-by-yields: true 
  save-extensions: ['pdf', 'png']

'h_ncleanjetspass_S5':
  y-axis-format: "%1% / bin"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf', 'png']


#b jet multiplicities
'h_ncleanbjetspass_notausf_S1':
  y-axis-format: "%1% / bin"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf', 'png']

'h_ncleanbjetspass_S2':
  y-axis-format: "%1% / bin"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf', 'png']

'h_ncleanbjetspass_S3':
  y-axis-format: "%1% / bin"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf', 'png']

'h_ncleanbjetspass_S4':
  y-axis-format: "%1% / bin"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf', 'png']

'h_ncleanbjetspass_S5':
  y-axis-format: "%1% / bin"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf', 'png']


#PV
'h_nvtx_notausf_S1':
  y-axis-format: "%1% / bin"
  save-extensions: ['pdf', 'png']

'h_nvtx_S2':
  y-axis-format: "%1% / bin"
  save-extensions: ['pdf', 'png']

'h_nvtx_S3':
  y-axis-format: "%1% / bin"
  save-extensions: ['pdf', 'png']

'h_nvtx_S4':
  y-axis-format: "%1% / bin"
  save-extensions: ['pdf', 'png']

'h_nvtx_S5':
  y-axis-format: "%1% / bin"
  save-extensions: ['pdf', 'png']


#MET pt
'h_met_pt_notausf_S1':
  save-extensions: ['pdf', 'png']

'h_met_pt_S2':
  save-extensions: ['pdf', 'png']

'h_met_pt_S3':
  save-extensions: ['pdf', 'png']

'h_met_pt_S4':
  save-extensions: ['pdf', 'png']

'h_met_pt_S5':
  save-extensions: ['pdf', 'png']


#MET phi
'h_met_phi_notausf_S1':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_met_phi_S2':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_met_phi_S3':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_met_phi_S4':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_met_phi_S5':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']


#Muon pt
'h_muon1_pt_notausf_S1':
  save-extensions: ['pdf','png']

'h_muon1_pt_S2':
  save-extensions: ['pdf','png']

'h_muon1_pt_S3':
  save-extensions: ['pdf','png']

'h_muon1_pt_S4':
  save-extensions: ['pdf','png']

'h_muon1_pt_S5':
  save-extensions: ['pdf','png']


#Muon eta
'h_muon1_eta_notausf_S1':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_muon1_eta_S2':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_muon1_eta_S3':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_muon1_eta_S4':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_muon1_eta_S5':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']


#Muon + MET MT
'h_muMET_mt_notausf_S1':
  save-extensions: ['pdf', 'png']

'h_muMET_mt_S2':
  save-extensions: ['pdf', 'png']

'h_muMET_mt_S3':
  save-extensions: ['pdf', 'png']

'h_muMET_mt_S4':
  save-extensions: ['pdf', 'png']

'h_muMET_mt_S5':
  save-extensions: ['pdf', 'png']


#tau pt
'h_tau1_pt_S2':
  save-extensions: ['pdf', 'png']

'h_tau1_pt_S3':
  save-extensions: ['pdf', 'png']

'h_tau1_pt_S4':
  save-extensions: ['pdf', 'png']

'h_tau1_pt_S5':
  save-extensions: ['pdf', 'png']


#tau eta
'h_tau1_eta_S2':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_tau1_eta_S3':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_tau1_eta_S4':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_tau1_eta_S5':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']


#tau decayMode
'h_tau1_decayMode_S2':
  y-axis-format: "%1% / bin"
  save-extensions: ['pdf', 'png']

'h_tau1_decayMode_S3':
  y-axis-format: "%1% / bin"
  save-extensions: ['pdf', 'png']

'h_tau1_decayMode_S4':
  y-axis-format: "%1% / bin"
  save-extensions: ['pdf', 'png']

'h_tau1_decayMode_S5':
  y-axis-format: "%1% / bin"
  save-extensions: ['pdf', 'png']


#Muon tau dR
'h_mutau_dR_S2':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_mutau_dR_S3':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_mutau_dR_S4':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_mutau_dR_S5':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']


#Muon tau mass
'h_mutau_mass_S2':
  save-extensions: ['pdf', 'png']

'h_mutau_mass_S3':
  save-extensions: ['pdf', 'png']

'h_mutau_mass_S4':
  save-extensions: ['pdf', 'png']

'h_mutau_mass_S5':
  save-extensions: ['pdf', 'png']


#jet ht for bSF check
'h_jet_ht_S3':
  rebin: 2
  save-extensions: ['pdf', 'png']

'h_jet_ht_S4':
  rebin: 2
  save-extensions: ['pdf', 'png']

'h_jet_ht_S5':
  rebin: 2
  save-extensions: ['pdf', 'png']


#jet1 pt
'h_jet1_pt_notausf_S1':
  save-extensions: ['pdf', 'png']

'h_jet1_pt_S2':
  save-extensions: ['pdf', 'png']

'h_jet1_pt_S3':
  save-extensions: ['pdf', 'png']

'h_jet1_pt_S4':
  save-extensions: ['pdf', 'png']

'h_jet1_pt_S5':
  save-extensions: ['pdf', 'png']


#jet1 eta
'h_jet1_eta_notausf_S1':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_jet1_eta_S2':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_jet1_eta_S3':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_jet1_eta_S4':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_jet1_eta_S5':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']


#jet1 btag
'h_jet1_btag_notausf_S1':
  y-axis-format: "%1% / %2$.2f units"
  save-extensions: ['pdf', 'png']

'h_jet1_btag_S2':
  y-axis-format: "%1% / %2$.2f units"
  save-extensions: ['pdf', 'png']

'h_jet1_btag_S3':
  y-axis-format: "%1% / %2$.2f units"
  save-extensions: ['pdf', 'png']

'h_jet1_btag_S4':
  y-axis-format: "%1% / %2$.2f units"
  save-extensions: ['pdf', 'png']

'h_jet1_btag_S5':
  y-axis-format: "%1% / %2$.2f units"
  save-extensions: ['pdf', 'png']


#jet2 pt
'h_jet2_pt_S4':
  save-extensions: ['pdf', 'png']

'h_jet2_pt_S5':
  save-extensions: ['pdf', 'png']


#jet2 eta
'h_jet2_eta_S4':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_jet2_eta_S5':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']


#jet2 btag
'h_jet2_btag_S4':
  y-axis-format: "%1% / %2$.2f units"
  save-extensions: ['pdf', 'png']

'h_jet2_btag_S5':
  y-axis-format: "%1% / %2$.2f units"
  save-extensions: ['pdf', 'png']


#jet3 pt
'h_jet3_pt_S4':
  save-extensions: ['pdf', 'png']

'h_jet3_pt_S5':
  save-extensions: ['pdf', 'png']


#jet3 eta
'h_jet3_eta_S4':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_jet3_eta_S5':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']


#jet3 btag
'h_jet3_btag_S4':
  y-axis-format: "%1% / %2$.2f units"
  save-extensions: ['pdf', 'png']

'h_jet3_btag_S5':
  y-axis-format: "%1% / %2$.2f units"
  save-extensions: ['pdf', 'png']


#bjet at step5
'h_bjet1_pt_S5':
  save-extensions: ['pdf', 'png']

'h_bjet1_eta_S5':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

##st_met
#'h_st_met_S4':
#  rebin: 2
#  save-extensions: ['pdf', 'png']
#
#'h_st_met_binwidth_S4':
#  y-axis: "Events / GeV"
#  y-axis-format: "%1%"
#  scale-option: "WIDTH"
#  rebin: 2
#  log-y: true
#  log-y-axis-range: [0.02, 200]
#  save-extensions: ['pdf', 'png']
#
#'h_st_met_S5':
#  rebin: 2
#  save-extensions: ['pdf', 'png']
#
#'h_st_met_binwidth_S5':
#  y-axis: "Events / GeV"
#  y-axis-format: "%1%"
#  scale-option: "WIDTH"
#  rebin: 2
#  log-y: true
#  log-y-axis-range: [0.02, 110]
#  save-extensions: ['pdf', 'png']
