'h_ncleanjetspass_yield_S5':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  signal-normalize-data: false
  sort-by-yields: true
  save-extensions: ['pdf', 'png']
  for-yields: true
  yields-table-order: 4
  yields-title: 'Final selection'
  #post-fit: true
